apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: highflame-storageclass
parameters:
  fsType: ext4
  type: gp3
  encrypted: "true"
  # kmsKeyId: <kms_key_arn>
  # tagSpecification_1: Environment=prod
  # tagSpecification_3: Project=highflame
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true