fullnameOverride: "highflame-collector"

livenessProbe:
  httpGet:
    path: /
    port: 13133
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

readinessProbe:
  httpGet:
    path: /
    port: 13133
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

nodeSelector:
  kube/nodegroup: "general"

podRestart:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  type: NodePort
  ports:
    - name: otlp-grpc
      port: 4317
    - name: otlp-http
      port: 4318
    - name: metrics
      port: 8888
    - name: healthz
      port: 13133

image:
  repository: "${DOCKER_IMAGE}"
  pullPolicy: Always
  tag: ${IMAGE_TAG}

imagePullSecrets:
  - name: highflame-registry-secret

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1024Mi
    cpu: 200m

secrets:
  enabled: true
  secretData:
    # Please refer https://github.com/highflame-ai/highflame-iac/blob/main/docs/service-vars.md

ingresses:
  enabled: true
  items:

    - name: http
      className: azure-application-gateway
      servicePort: 4318
      annotations:
        appgw.ingress.kubernetes.io/use-private-ip: "false"
        appgw.ingress.kubernetes.io/ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        appgw.ingress.kubernetes.io/backend-protocol: "http"
        appgw.ingress.kubernetes.io/request-timeout: "300"

        appgw.ingress.kubernetes.io/health-probe-path: "/healthz"
        appgw.ingress.kubernetes.io/health-probe-status-codes: "200"
        appgw.ingress.kubernetes.io/health-probe-interval: "15"
        appgw.ingress.kubernetes.io/health-probe-timeout: "5"
        appgw.ingress.kubernetes.io/health-probe-unhealthy-threshold: "2"

      tls:
        - hosts:
            - otel-http.api.example.com
          secretName: otel-http-tls
      hosts:
        - host: otel-http.api.example.com
          paths:
            - path: /
              pathType: Prefix

    - name: grpc
      className: azure-application-gateway
      servicePort: 4317
      annotations:
        appgw.ingress.kubernetes.io/use-private-ip: "false"
        appgw.ingress.kubernetes.io/ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        appgw.ingress.kubernetes.io/backend-protocol: "http"
        appgw.ingress.kubernetes.io/request-timeout: "300"
        appgw.ingress.kubernetes.io/health-probe-path: "/healthz"
        appgw.ingress.kubernetes.io/health-probe-status-codes: "200"
        appgw.ingress.kubernetes.io/health-probe-interval: "15"
        appgw.ingress.kubernetes.io/health-probe-timeout: "5"
        appgw.ingress.kubernetes.io/health-probe-unhealthy-threshold: "2"

      tls:
        - hosts:
            - otel-grpc.api.example.com
          secretName: otel-grpc-tls
      hosts:
        - host: otel-grpc.api.example.com
          paths:
            - path: /
              pathType: Prefix