fullnameOverride: "highflame-Observatory"

livenessProbe:
  httpGet:
    path: /health
    port: 8090
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

readinessProbe:
  httpGet:
    path: /ready
    port: 8090
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

nodeSelector:
  kube/nodegroup: "general"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  annotations:
    cloud.google.com/backend-config: '{ "default" : "highflame-observatory-default" }'
  type: NodePort
  protocol: TCP
  port: 8090

gceIngress:
  backendConfigs:
    enabled: true
    items:
    - name: default
      timeoutSec: 300
      healthCheck:
        checkIntervalSec: 15
        timeoutSec: 5
        healthyThreshold: 2
        unhealthyThreshold: 2
        type: HTTP
        requestPath: "/ready"
        port: 8090
      securityPolicy:
        enabled: true
        name: "highflame-cloud-security-policy"

image:
  repository: "${DOCKER_IMAGE}"
  pullPolicy: IfNotPresent
  tag: ${IMAGE_TAG}

imagePullSecrets:
  - name: highflame-registry-secret

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1024Mi
    cpu: 200m

volumes:
  - name: auth-keys
    secret:
      secretName: highflame-auth-keys
      optional: false

volumeMounts:
  - name: auth-keys
    mountPath: "/app/config/jwt/jwt-public.pem"
    readOnly: true
    subPath: jwt-public.pem

secrets:
  enabled: true
  secretData:
    # Please refer https://github.com/highflame-ai/highflame-iac/blob/main/docs/service-vars.md