gceIngress:
  frontendConfig:
    enabled: true
    sslPolicy: 
      enabled: true
      name: highflame-cloud-ssl-policy
  uniqueManagedCertificate:
    enabled: true
    certificateList:
      - certName: control-cert
        domain: control.example.com
      - certName: data-cert
        domain: api.example.com
      - certName: gateway-cert
        domain: gateway.example.com
      - certName: studio-cert
        domain: studio.example.com
ingress:
  enabled: true
  annotations:
    networking.gke.io/managed-certificates: "control-cert, data-cert, gateway-cert, studio-cert"
    kubernetes.io/ingress.global-static-ip-name: highflame-poc-ingress-ip
    networking.gke.io/v1beta1.FrontendConfig: highflame-ingress
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: "gce"
  hosts:
    - host: control.example.com
      paths:
        - path: /v1/admin/
          pathType: Prefix
          serviceName: "highflame-admin"
          servicePort: 8040
        - path: /v2/admin/
          pathType: Prefix
          serviceName: "highflame-admin"
          servicePort: 8040
        - path: /v1/auth
          pathType: Prefix
          serviceName: "highflame-authn"
          servicePort: 8051
    - host: api.example.com
      paths:
        - path: /v1/cerberus
          pathType: Prefix
          serviceName: "highflame-cerberus"
          servicePort: 8082
        - path: /v1/obs
          pathType: Prefix
          serviceName: "highflame-observatory"
          servicePort: 8090
        - path: /v1/shield
          pathType: Prefix
          serviceName: "highflame-shield"
          servicePort: 8070
    - host: gateway.example.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: "highflame-firehog"
          servicePort: 8080
    - host: studio.example.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: "highflame-studio"
          servicePort: 3000