fullnameOverride: "highflame-guard"

livenessProbe:
  httpGet:
    path: /livez
    port: 8013
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

readinessProbe:
  httpGet:
    path: /healthz
    port: 8013
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

nodeSelector:
  kube/nodegroup: "gpu"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  type: ClusterIP
  protocol: TCP
  port: 8013

image:
  repository: "${DOCKER_IMAGE}"
  pullPolicy: Always
  tag: ${IMAGE_TAG}

imagePullSecrets:
  - name: highflame-registry-secret

resources:
  requests:
    memory: 10Gi
    cpu: 3000m
  limits:
    memory: 14Gi
    cpu: 3500m

secrets:
  enabled: true
  secretData:
    # Please refer https://github.com/highflame-ai/highflame-iac/blob/main/docs/service-vars.md