fullnameOverride: "highflame-firehog"

livenessProbe:
  httpGet:
    path: /livez
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

readinessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

nodeSelector:
  kube/nodegroup: "general"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  annotations:
    cloud.google.com/backend-config: '{ "default" : "highflame-firehog-default" }'
  type: NodePort
  protocol: TCP
  port: 8080

gceIngress:
  backendConfigs:
    enabled: true
    items:
    - name: default
      timeoutSec: 300
      healthCheck:
        checkIntervalSec: 15
        timeoutSec: 5
        healthyThreshold: 2
        unhealthyThreshold: 2
        type: HTTP
        requestPath: "/healthz"
        port: 8080
      securityPolicy:
        enabled: true
        name: "highflame-cloud-security-policy"

image:
  repository: "${DOCKER_IMAGE}"
  pullPolicy: Always
  tag: ${IMAGE_TAG}

imagePullSecrets:
  - name: highflame-registry-secret

resources:
  requests:
    memory: 512Mi
    cpu: 200m
  limits:
    memory: 1024Mi
    cpu: 500m

secrets:
  enabled: true
  secretData:
    # Please refer https://github.com/highflame-ai/highflame-iac/blob/main/docs/service-vars.md